Update auto_bulid.yaml

diff --git a/.github/workflows/auto_bulid.yaml b/.github/workflows/auto_bulid.yaml
--- a/.github/workflows/auto_bulid.yaml
+++ b/.github/workflows/auto_bulid.yaml
@@ -21,6 +21,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
+        pip install -r requirements.txt
         pip install pyinstaller
 
     - name: Build executable
@@ -29,7 +30,13 @@ jobs:
 
     - name: Extract version from version.txt
       id: extract_version
-      run: echo "::set-output name=version::$(cat version.txt)"
+      run: |
+        if [ -f "version.txt" ]; then
+          echo "::set-output name=version::$(cat version.txt)"
+        else
+          echo "version.txt not found."
+          exit 1
+        fi
 
   release:
     needs: build
@@ -68,4 +75,4 @@ jobs:
       uses: actions/upload-artifact@v2
       with:
         name: PORTMK-${{ steps.extract_version.outputs.version }}
-        path: bulid
+        path: dist
